# NumPy (Numerical Python)

* 수학 및 과학적 연산을 쉽고 빠르게 지원
* 다차원 <font color = 'blue'>행렬</font>(Array/Matrix)을 효과적으로 처리
* 일반적으로 <font color = 'red'>같은 데이터 타입 값</font>으로 구성
* https://numpy.org

In [1]:
import warnings
warnings.filterwarnings('ignore')

# I. NumPy Package <font color='blue'>import ~ as

In [2]:
import numpy as np

* Version Check

In [3]:
np.__version__

'2.2.5'

# II. Array 생성

* Python <font color = 'blue'>List 구조</font>를 사용

>## 1) Scalar - <font color='red'>0D Array</font> - <font color='blue'>Rank0 Tensor

In [4]:
a0 = np.array(9)

In [5]:
print(a0)

9


>## 2) Vector - <font color='red'>1D Array</font> - <font color='blue'>Rank1 Tensor

In [6]:
a1 = np.array([1, 3, 5, 7, 9])

In [7]:
print(a1)

[1 3 5 7 9]


In [8]:
a1[2]

np.int64(5)

In [ ]:
a1[1:3]

array([3, 5])

>## 3) Matrix - <font color='red'>2D Array</font> - <font color='blue'>Rank2 Tensor

In [10]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [11]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* a2[행]

In [12]:
a2[1]

array([4, 5, 6])

* a2[행, 열]

In [13]:
a2[1, 1]

np.int64(5)

* a2[<font color = 'blue'>행</font>, 열] -> ex) '0:3' 은 0~3전까지, ' : ' 은 행 또는 열 전체

In [14]:
a2[:, 1]

array([2, 5, 8])

In [17]:
a2[0:2, 2]

array([3, 6])

In [18]:
a2[0:2, 0:2]

array([[1, 2],
       [4, 5]])

>## 4) Array - <font color='red'>3D Array</font> - <font color='blue'>Rank3 Tensor

* 3차원(차원, 행, 열)

In [24]:
a3 = np.array([
               [
                [1, 2],
                [3, 4]
               ],
               [
                [5, 6],
                [7, 8]
               ],
               [
                [9, 10],
                [11, 12]
               ]
             ])

In [20]:
a3.shape

(3, 2, 2)

In [21]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* a3[축]

In [22]:
a3[1]

array([[5, 6],
       [7, 8]])

In [26]:
a3[0]

array([[1, 2],
       [3, 4]])

* a3[축, 행]

In [25]:
a3[1, 1]

array([7, 8])

* a3[축, 행, 열]

In [27]:
a3[1, 1, 1]

np.int64(8)

* a3[<font color = 'blue'>축</font>, 행, 열]

In [28]:
a3[:, 0, 0]

array([1, 5, 9])

In [29]:
a3[:, 0:2, 0:2]

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [30]:
a3[:, 0:1, 0:1]

array([[[1]],

       [[5]],

       [[9]]])

* a3[<font color = 'blue'>축</font>, <font color = 'blue'>행</font>, 열]

In [31]:
a3[:, :, 0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [32]:
a4 = np.array([
               [
                [1, 2, 20],
                [3, 4, 21]
               ],
               [
                [5, 6, 22],
                [7, 8, 23]
               ],
               [
                [9, 10, 24],
                [11, 12, 25]
               ]
             ])

In [33]:
a4[2, 0, 1]

np.int64(10)

In [34]:
a4[:, 0:2, 0:1]

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]])

In [35]:
a4[1, :, 0]

array([5, 7])

In [36]:
a5 = np.array([
               [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
               ],
               [
                [11, 12, 13],
                [14, 15, 16],
                [17, 18, 19]
               ],
               [
                [21, 22, 23],
                [24, 25, 26],
                [27, 28, 29]
               ]
             ])

In [37]:
a5[0:3, :, 2]

array([[ 3,  6,  9],
       [13, 16, 19],
       [23, 26, 29]])

In [38]:
a5[2, 0, 0]

np.int64(21)

# III. AR<font color='red'>.shape</font> and AR<font color='blue'>.reshape( )

In [39]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [40]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


>## 1) <font color='red'>.shape

* 행렬 크기

In [41]:
AR.shape

(12,)

* 행렬 차원

In [42]:
AR.ndim

1

* 행렬 원소 개수

In [43]:
AR.size

12

>## 2) <font color='blue'>.reshape(3, 4) : 차원 변경

* <font color = 'blue'>.reshape(</font>행, 열<font color = 'blue'>)</font> -> 1차원을 2차원으로 변경 (조건 : 배수)

In [44]:
AR2 = AR.reshape(3, 4)

In [45]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* 행렬 크기

In [46]:
AR2.shape

(3, 4)

* 행렬 차원

In [47]:
AR2.ndim

2

* 행렬 원소 개수

In [48]:
AR2.size

12

>## 3) <font color='blue'>.reshape(3, 2, 2)

* .reshape(<font color = 'red'>축</font>, 행, 열) -> 3차원으로 변경

In [49]:
AR3 = AR.reshape(3, 2, 2)

In [50]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* 행렬의 크기

In [51]:
AR3.shape

(3, 2, 2)

* 행렬의 차원

In [52]:
AR3.ndim

3

* 행렬의 원소 개수

In [53]:
AR3.size

12

>## 4) .reshape(<font color = 'red'>-1</font>, 1)

* .reshape(<font color = 'red'>-1</font>, 1) : (12, 1)와 같다 / -1을 자동으로 12로

In [55]:
AR

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
AR.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

   * .reshape(1, <font color = 'blue'>12</font>)

In [57]:
AR2.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [58]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* <font color = 'blue'>.flatten( ) : 1차원으로 변경

In [60]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IV. 범위 지정(arange) 함수

>## 1) 연속된 10개 값 생성 (기본 : 0부터 시작)
* -> 파이썬에서 배열

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 2) 1부터 9까지 <font color = 'blue'>1간격</font>으로 생성

In [62]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 3) 1부터 9까지 <font color = 'red'>2간격</font>으로 생성

In [63]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

>## 4) Array 생성 후 <font color = 'blue'>.reshape( )</font> 적용

In [64]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# V. 특별한 형태의 Array 생성

>## 1) 0과 1로만 구성된 Array

* <font color = 'blue'>0으로만 구성

In [65]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* <font color = 'blue'>1로만 구성

In [67]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 산술연산을 적용하여 <font color = 'blue'>'9'로만 구성</font>된 행렬 생성

In [69]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

>## 2) 3 x 3 <font color = 'red'>단위행렬

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

>## 3) 난수 Array 생성

* <font color = 'blue'>실수</font> 난수 생성
 - (축, 행, 열)

In [71]:
np.random.rand(3, 2, 2)

array([[[0.05017451, 0.96444687],
        [0.40856771, 0.99159239]],

       [[0.55199848, 0.10526446],
        [0.80806167, 0.87659217]],

       [[0.88340728, 0.20776976],
        [0.60598177, 0.17193004]]])

* 주어진 <font color = 'blue'>정수</font> 범위에서 난수 생성
 - 1 ~ 44 사이
 - 복원 추출
 - (행, 열)

In [73]:
np.random.randint(1, 45, size = (5, 6))

array([[41,  6,  5, 39,  7, 33],
       [38,  9, 19,  3, 42, 40],
       [30, 33, 24, 32, 43,  6],
       [34, 34, 32,  2, 32, 36],
       [27, 32, 29, 15, 12, 13]], dtype=int32)

* np.random.<font color = 'red'>seed( )</font>
 - 의사난수(Pseudo Random Number) 생성 초기값 지정
 - <font color = 'red'>항상 같은 난수 생성</font>
 - 비복원 추출

In [81]:
np.random.seed(2045)  #seed값을 넣으면 동일하게 나온다

np.random.choice(np.arange(1, 46), size = (5, 6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

* <font color = 'blue'>shuffle( )</font>
 - 원소 섞기

In [82]:
TA = np.arange(1, 10)

TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.random.shuffle(TA)  #1~9까지 섞기

TA

array([1, 6, 5, 2, 9, 4, 7, 8, 3])

# VI. Array 연산

In [85]:
A1 = np.array([85, 93, 75, 97, 69])

A2 = np.array([91, 90, 85, 97, 89])

A3 = np.array([[85, 93, 75],
               [90, 84, 97],
               [99, 91, 80]])

>## 1) 기본 연산

* 각각의 <font color = 'blue'>행과 열의 값을 매칭</font>하여 연산 수행

In [86]:
A1 + A2

array([176, 183, 160, 194, 158])

In [87]:
A2 - A1

array([ 6, -3, 10,  0, 20])

In [88]:
A1 * A2

array([7735, 8370, 6375, 9409, 6141])

In [89]:
A2 / A1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [90]:
A1 * 3

array([255, 279, 225, 291, 207])

In [91]:
A1 ** 2

array([7225, 8649, 5625, 9409, 4761])

>## 2) 통계량 연산

* 총합

In [92]:
A1.sum()

np.int64(419)

* 평균

In [93]:
A2.mean()

np.float64(90.4)

* 분산
 - 'ddof = 0'

In [94]:
A2.var()

np.float64(15.040000000000001)

* 표준 편차
 - 'ddof = 0'

In [95]:
A2.std()

np.float64(3.8781438859330635)

* 최소값

In [96]:
A2.min()

np.int64(85)

> * A3 전체 최소값

  

In [97]:
A3.min()

np.int64(75)

> * A3 각 열의 최소값

In [98]:
A3.min(axis = 0)

array([85, 84, 75])

> * A3 각 행의 최소값

In [101]:
z = np.arange(36).reshape(3,4,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [104]:
z.min(axis = 2)

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [99]:
A3.min(axis = 1)

array([75, 84, 80])

In [100]:
A3.min(axis = 1, keepdims = True)

array([[75],
       [84],
       [80]])

* 최대값

In [105]:
A2.max()

np.int64(97)

> * A3 전체 최대값

In [106]:
A3.max()

np.int64(99)

> * A3 각 열의 최대값

In [107]:
A3.max(axis = 0)

array([99, 93, 97])

> * A3 각 행의 최대값

In [108]:
A3.max(axis = 1)

array([93, 97, 99])

In [109]:
A3.max(axis = 1, keepdims = True)

array([[93],
       [97],
       [99]])

* 누적(Cumulative)합

In [ ]:
A1.cumsum()

array([ 85, 178, 253, 350, 419])

* 누적(Cumulative)곱

In [ ]:
A1.cumprod()

array([        85,       7905,     592875,   57508875, 3968112375])

# VII. Matrix 연산

* M1, M2 지정

In [110]:
M1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [111]:
print(M1)

[[2 4]
 [6 8]]


In [112]:
M2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [113]:
print(M2)

[[3 5]
 [7 9]]


>## 1) Matrix 곱

* <font color='red'>M1 @ M2

In [ ]:
M1.dot(M2) #행렬 연산

array([[ 34,  46],
       [ 74, 102]])

* <font color='blue'>M2 @ M1

In [115]:
np.dot(M2, M1)

array([[ 36,  52],
       [ 68, 100]])

* <font color='red'>Warning</font>: M1 * M2

In [116]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [117]:
M2 * M1

array([[ 6, 20],
       [42, 72]])

>## 2) 전치 행렬

* M1의 전치 행렬

In [118]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

* M2의 전치 행렬

In [119]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [120]:
M2.T

array([[3, 7],
       [5, 9]])

#
#
#
# End Of Document
#
#
#